import { Database } from 'bun:sqlite'
import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const TYPE_MAP: Record<string, string> = {
  INTEGER: 'number',
  REAL: 'number',
  TEXT: 'string',
  JSON: 'string',
  BLOB: 'Buffer',
  DATETIME: 'string',
}

function sqliteType(colType: string): string {
  const upper = colType.toUpperCase()
  for (const [key, ts] of Object.entries(TYPE_MAP)) {
    if (upper.includes(key)) return ts
  }
  return 'string'
}

function isGenerated(dfltValue: string | null, tsType: string): boolean {
  if (!dfltValue) return false
  const upper = dfltValue.toUpperCase()
  return upper.includes('CURRENT_TIMESTAMP') || upper.includes('AUTOINCREMENT')
}

interface Column {
  name: string
  type: string
  notnull: number
  dflt_value: string | null
  pk: number
}

interface TableInfo {
  name: string
  columns: Column[]
  fkColumns: Set<string>
}

async function introspect(db: Database): Promise<TableInfo[]> {
  const tables = db
    .query(
      `
    SELECT name FROM sqlite_master
    WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND name != '_migrations'
    ORDER BY name
  `,
    )
    .all() as { name: string }[]

  return tables.map(({ name }) => {
    const columns = db
      .query(`SELECT * FROM pragma_table_info('${name}') ORDER BY cid`)
      .all() as Column[]

    const fks = db.query(`SELECT * FROM pragma_foreign_key_list('${name}')`).all() as {
      from: string
    }[]

    const fkColumns = new Set(fks.map((f) => f.from))

    return { name, columns, fkColumns }
  })
}

function tableNameToType(name: string): string {
  return name
    .split('_')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
}

function columnType(col: Column, isForeignKey: boolean): string {
  const tsType = sqliteType(col.type)
  const isPk = col.pk === 1
  // SQLite pragma may omit NOT NULL for FK columns; treat them as NOT NULL
  const notNull = col.notnull === 1 || isPk || isForeignKey
  const generated = isGenerated(col.dflt_value, tsType)

  // INTEGER PK is auto-increment in SQLite => Generated<number>
  if (isPk && tsType === 'number') {
    return `Generated<${tsType}>`
  }

  if (generated) {
    return `Generated<${tsType}>`
  }

  return notNull ? tsType : `${tsType} | null`
}

function generateTypes(tables: TableInfo[]): string {
  const lines: string[] = [
    '// Auto-generated by codegen.ts. Do not edit manually.',
    '// Generated at: ' + new Date().toISOString(),
    '',
    "import type { Generated } from 'kysely'",
    '',
  ]

  for (const table of tables) {
    const typeName = tableNameToType(table.name) + 'Table'
    lines.push(`export interface ${typeName} {`)

    for (const col of table.columns) {
      lines.push(`  ${col.name}: ${columnType(col, table.fkColumns.has(col.name))}`)
    }

    lines.push('}')
    lines.push('')
  }

  lines.push('export interface DatabaseSchema {')
  for (const table of tables) {
    const key = table.name
    const typeName = tableNameToType(table.name) + 'Table'
    lines.push(`  ${key}: ${typeName}`)
  }
  lines.push('}')

  return lines.join('\n') + '\n'
}

async function main() {
  const dbPath = process.env.DATABASE_URL || 'db.sqlite'
  const outFile = join(import.meta.dir, 'kysely-types.ts')

  const db = new Database(dbPath, { create: true })
  const tables = await introspect(db)
  db.close()

  const output = generateTypes(tables)
  await writeFile(outFile, output)

  console.log(`Generated ${outFile} (${tables.length} tables)`)
}

main().catch((err) => {
  console.error('Codegen failed:', err)
  process.exit(1)
})
