// Auto-generated by codegen.ts. Do not edit manually.
// Generated at: 2026-07-15T05:10:40.698Z

import type { Generated } from 'kysely'

export interface ApiTokensTable {
  id: Generated<number>
  user_id: number
  project_id: string
  name: string
  token_hash: string
  permissions: string
  created_at: Generated<string>
  revoked_at: string | null
}

export interface AuditEventsTable {
  id: Generated<number>
  workspace_id: string
  user_id: number
  action: string
  target_type: string
  target_id: string
  metadata: string | null
  created_at: Generated<string>
}

export interface DocumentsTable {
  id: string
  path: string
  user_id: number
  project_id: string
  content: string
  access_mode: string
  access_secret: string | null
  size_bytes: number
  created_at: Generated<string>
  updated_at: Generated<string>
  version: number
  workspace_id: string
}

export interface KyselyMigrationTable {
  name: string
  timestamp: string
}

export interface KyselyMigrationLockTable {
  id: string
  is_locked: number
}

export interface MemberRecoveryLinksTable {
  id: string
  workspace_id: string
  user_id: number
  secret_hash: string
  expires_at: string
  used_at: string | null
  revoked_at: string | null
  created_by: number
  created_at: Generated<string>
}

export interface ProjectsTable {
  id: string
  user_id: number
  name: string
  created_at: Generated<string>
}

export interface SessionsTable {
  id: string
  user_id: number
  token_hash: string
  expires_at: string
  revoked_at: string | null
  created_at: Generated<string>
}

export interface UsersTable {
  id: Generated<number>
  github_id: string
  email: string | null
  display_name: string | null
  created_at: Generated<string>
  kind: string
}

export interface WorkspaceInvitesTable {
  id: string
  workspace_id: string
  role: string
  secret_hash: string
  expires_at: string | null
  max_uses: number | null
  use_count: number
  created_by: number
  revoked_at: string | null
  created_at: Generated<string>
}

export interface WorkspaceMembersTable {
  id: Generated<number>
  workspace_id: string
  user_id: number
  role: string
  joined_at: Generated<string>
  removed_at: string | null
}

export interface WorkspacesTable {
  id: string
  project_id: string
  name: string
  created_by: number
  created_at: Generated<string>
  deleted_at: string | null
}

export interface DatabaseSchema {
  api_tokens: ApiTokensTable
  audit_events: AuditEventsTable
  documents: DocumentsTable
  kysely_migration: KyselyMigrationTable
  kysely_migration_lock: KyselyMigrationLockTable
  member_recovery_links: MemberRecoveryLinksTable
  projects: ProjectsTable
  sessions: SessionsTable
  users: UsersTable
  workspace_invites: WorkspaceInvitesTable
  workspace_members: WorkspaceMembersTable
  workspaces: WorkspacesTable
}
