// Auto-generated by codegen.ts. Do not edit manually.
// Generated at: 2026-07-09T06:51:15.779Z

import type { Generated } from 'kysely'

export interface ApiTokensTable {
  id: Generated<number>
  user_id: number
  project_id: string
  name: string
  token_hash: string
  permissions: string
  created_at: Generated<string>
  revoked_at: string | null
}

export interface DocumentsTable {
  id: string
  path: string
  user_id: number
  project_id: string
  content: string
  access_mode: string
  access_secret: string | null
  size_bytes: number
  created_at: Generated<string>
  updated_at: Generated<string>
  version: number
}

export interface KyselyMigrationTable {
  name: string
  timestamp: string
}

export interface KyselyMigrationLockTable {
  id: string
  is_locked: number
}

export interface ProjectsTable {
  id: string
  user_id: number
  name: string
  created_at: Generated<string>
}

export interface UsersTable {
  id: Generated<number>
  github_id: string
  email: string | null
  display_name: string | null
  created_at: Generated<string>
}

export interface DatabaseSchema {
  api_tokens: ApiTokensTable
  documents: DocumentsTable
  kysely_migration: KyselyMigrationTable
  kysely_migration_lock: KyselyMigrationLockTable
  projects: ProjectsTable
  users: UsersTable
}
