// Auto-generated by codegen.ts. Do not edit manually.
// Generated at: 2026-06-12T06:16:34.206Z

import type { Generated } from 'kysely'

export interface ApiTokensTable {
  id: Generated<number>
  user_id: number
  name: string
  token_hash: string
  permissions: string
  created_at: Generated<string>
  revoked_at: string | null
}

export interface DocumentsTable {
  id: string
  path: string
  user_id: number
  content: string
  access_mode: string
  access_secret: string | null
  size_bytes: number
  created_at: Generated<string>
  updated_at: Generated<string>
}

export interface UsersTable {
  id: Generated<number>
  github_id: string
  email: string | null
  display_name: string | null
  created_at: Generated<string>
}

export interface DatabaseSchema {
  api_tokens: ApiTokensTable
  documents: DocumentsTable
  users: UsersTable
}
